version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_NAME: shop
      DATABASE_USER: manager
      DATABASE_PASSWORD: pass_word
      DATABASE_HOST: db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: shop
      MYSQL_USER: manager
      MYSQL_PASSWORD: pass_word
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
