# Generated by Django 5.1.3 on 2024-11-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prod',
        ),
    ]
